# Example tests with REST Client (VSCode Extension)

@url = http://localhost:5000/api
@json = content-type: application/json

###

GET {{url}}/challengeevents?term=

###

POST {{url}}/challengeevent
{{json}}

{
    "name": "new challengeevent"
}

###

PUT {{url}}/challengeevent
{{json}}

{
    "id": 1,
    "name": "challengeevent"
}

###

DELETE {{url}}/challengeevent/1
