# Example tests with REST Client (VSCode Extension)

@url = http://localhost:5002/api
@json = content-type: application/json

###

GET {{url}}/challengespecs?filter=play&term=

###

POST {{url}}/challengespec
{{json}}

{
    "name": "new challengespec"
}

###

PUT {{url}}/challengespec
{{json}}

{
    "id": 1,
    "name": "challengespec"
}

###

DELETE {{url}}/challengespec/1
