# Example tests with REST Client (VSCode Extension)

@url = http://localhost:5000/api
@json = content-type: application/json

###

GET {{url}}/sponsors?term=

###

POST {{url}}/sponsor
{{json}}

{
    "name": "new sponsor"
}

###

PUT {{url}}/sponsor
{{json}}

{
    "id": 1,
    "name": "sponsor"
}

###

DELETE {{url}}/sponsor/1
