name: License Header Check

on:
  pull_request:
    branches:
      - main

jobs:
  header-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Headers
        uses: cmu-sei/Crucible-Github-Actions/actions/header@header-v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
