name: CI

on:
  pull_request:
  release:
    types: ["published"]
  push:
    branches:
      - dev
      - test
      - next

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src/Gameboard.Api.sln -c Release --no-restore
      - name: Run unit tests
        run: dotnet test src/Gameboard.Api.Tests.Unit -c Test --no-restore
      - name: Run integration tests
        run: dotnet test src/Gameboard.Api.Tests.Integration -c Test --no-restore

  build:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: cmusei/gameboard-api

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: commit=${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
